accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import views, models

app_name = 'accounts'
urlpatterns = [
    url(r'^new-account/$', views.NewUser, name='newaccount'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^add-friend/$', views.AddFriend, name='addfriend'),
]

cal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cal import views, models

app_name = 'cal'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^newevent/$', views.newevent, name='newevent'),
    url(r'^events/(\d+)/', views.viewevent, name='viewevent'),
    url(r'^(?P<month>\d+)/(?P<year>\d+)$', views.home, name='another-month'),
    url(r'^delete_event/(?P<id>\d+)$', views.delete_event, name='delete_event'),
]

organiser/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cal import urls as cal_urls
from accounts import urls as accounts_urls

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^cal/', include(cal_urls, namespace="cal")),
    url(r'^accounts/', include(accounts_urls)),
]

cal/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from accounts.models import Account

class Events(models.Model):
    title = models.CharField(max_length=250)
    start_date = models.DateField(blank=False)
    start_time = models.TimeField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, default=1, related_name='creator')
    created = models.DateTimeField(auto_now=True)
    location = models.CharField(max_length=250, blank=True)
    attendees = models.ManyToManyField(
        Account, related_name='attendees', blank=True)
    private = models.BooleanField(default=False)
    description = models.TextField(blank=True)

    #Allows calendarify template tag to pull URLs for each event diplayed in a
    #calendar.
    def get_absolute_url(self):
        return reverse('cal:viewevent', args=[str(self.id)], current_app='cal')

cal/forms.py
from django.forms import ModelForm, DateField
from bootstrap_datepicker.widgets import DatePicker
from cal.models import Events
from accounts.models import Account
from django.contrib.auth.models import User
from datetime import date
from django import forms

class EventForm(ModelForm):
    #Meta class allows specification of which model fields required in form
    class Meta:
        model = Events
        exclude = ['created', 'creator', 'private']
        #Widgets allows us to add attributes to HTML for form
        widgets = {'title':forms.TextInput(attrs={'class':'form-control'}),
            'start_time':forms.TimeInput(attrs={
                'class':'datetimepicker3 form-control mb-2 mr-sm-2 mb-sm-0'}),
            'end_time':forms.TimeInput(attrs={
                'class':'datetimepicker3 form-control mb-2 mr-sm-2 mb-sm-0'}),
            'location':forms.TextInput(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control',
                'rows':10,
                'cols':64
            }),
        }

    #These are declared separately as a number of attributes need to be added.
    #This includes the datetimepicker class which user Jquery to display
    #Bootstrap datetimepicker.
    start_date = forms.DateField(widget = forms.DateInput(
        format="%d/%m/%Y",
        attrs={'class': 'datetimepicker4 form-control mb-2 mr-sm-2 mb-sm-0'}),
        input_formats=["%d/%m/%Y",],
        initial=date.today
        )

    end_date = forms.DateField(widget = forms.DateInput(
        attrs={'class': 'datetimepicker4 form-control mb-2 mr-sm-2 mb-sm-0'},
        format="%d/%m/%Y"),
        input_formats=["%d/%m/%Y",],
        required=False
        )

    #Sets up form class to take data (the user) from that is passed into the
    #view from the template and use that to pull the user's friends from the db.
    #This allows us to display the friends as tickbox options in the event form.
    def __init__(self, user=None, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['attendees'] = forms.ModelMultipleChoiceField(
                queryset=Account.objects.get(username=user).friends,
                widget=forms.CheckboxSelectMultiple,
                required=False,
                )

cal/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from datetime import date, datetime
from django.contrib import messages
from django.views.generic import DeleteView
from cal.forms import EventForm
from django.contrib.auth.models import User
from cal.models import Events
from accounts.models import Account
from cal.backend import calendar, date_format, user_or_attendee, add_end_date

def home(request, month=None, year=None):
    if month == None:
        _date = datetime.now()
    #If month/year supplied return calendar for that date.
    else:
        _date = date(int(year), int(month), 1)
    #User backend function to return dictionary required for calendar template.
    #tag.
    cal = calendar(_date, request)
    return render(request, 'calendar.html', cal)

def newevent(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            form = EventForm(data=request.POST)
            #Use backend.date_format function to format date for calendar.
            date = date_format(form)
            #Pass that info into the backend.calendar function.
            cal = calendar(date, request)
            if form.is_valid():
                event = form.save(commit=False)
                #Add creator from request data
                event.creator = request.user
                #Add end date if not supplied user backend function.
                event.end_date = add_end_date(event.end_date, event.start_date)
                form.save()
                #Use reverse to pull calendar view for the month the event
                #was created for
                return HttpResponseRedirect(reverse('cal:another-month',
                                            args=[cal['month'], cal['year']],
                                            current_app='cal'))
        else:
            form = EventForm(request.user.username)
            return render(request, 'event.html', {'form': form})
    else:
        #If user not logged in an error message will be displayed.
        messages.warning(request, "Please login to create an event!",
                        extra_tags="event-error")
    return redirect('cal:home')

def viewevent(request, id):
    #Receive ID from template/URL and pull correct event from db.
    instance = Events.objects.get(id=id)
    #Use backend.user_or_attendee function to check user can view/edit event.
    if user_or_attendee(request.user, instance):
        if request.method == 'POST':
            form = EventForm(data=request.POST, instance=instance)
            #Use backend.date_format function to format date for calendar.
            date = date_format(form)
            #Pass that info into the backend.calendar function.
            cal = calendar(date, request)
            if form.is_valid():
                event = form.save(commit=False)
                #Add creator from request data
                event.creator = request.user
                #Add end date if not supplied user backend function.
                event.end_date = add_end_date(event.end_date, event.start_date)
                form.save()
                #Use reverse to pull calendar view for the month the event
                #was created for
                return HttpResponseRedirect(reverse('cal:another-month',
                                            args=[cal['month'], cal['year']],
                                            current_app='cal'))
        else:
            form = EventForm(request.user.username, instance=instance)
        return render(request, 'view_event.html', {'form':form, 'id':id})
    else:
        #If user not logged in an error message will be displayed.
        messages.error(
            request, "You do not have permission to see this event",
            extra_tags="event-error")
        return redirect('cal:home')


def delete_event(request, id):
    #Check object can be pulled from db/exists.
    instance = get_object_or_404(Events, id=id)
    #Check user has permission to delete event.
    if user_or_attendee(request.user, instance):
        #Pull date so it can be passed as variables to calendar view.
        date = instance.start_date
        instance.delete()
    #Use reverse to pull calendar view for the month the event was on.
    return HttpResponseRedirect(reverse('cal:another-month', args=[
                                date.month, date.year], current_app='cal'))

cal/templates/calendar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Calendar - Home</title>
    <link rel="stylesheet" href="/static/cal/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/cal/calendar.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">

    <script type="text/javascript" src="/static/cal/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/static/cal/bootstrap/js/bootstrap.min.js"></script>

  </head>
  <body>
    <div class='container'>
        <div class='navbar-default nav'>
          <ul class="nav navbar-nav navbar-left">
            <div class='btn-group'>
              <div class='floatLeft col-md-*'>
                <form action="{% url 'cal:another-month' lastmonth lastyear %}">
                  <button class="btn btn-primary btn-md" id="last_month">Previous Month</button>
                </form>
              </div>
              <div class='floatRight col-md-*'>
                <form action="{% url 'cal:another-month' nextmonth nextyear %}">
                  <button class="btn btn-primary btn-md" id="next_month">Next Month</button>
                </form>
              </div>

              <div class=btn-group>
                <div class="new_event_div">
                  <form action="/cal/newevent/" method="get">
                    <button class="btn btn-primary btn-md" id="new_event">Create New Event</button>
                  </form>
                </div>
              </div>
            </div>
          </ul>

          {% if request.user.username %}
            <ul class='nav navbar-nav navbar-right'>
              <li class="navbar-text">Logged in as {{ request.user.username }}</li>
              <li><a id="logout" href="{% url 'accounts:logout' %}">Log out</a></li>

              <div class="navbar-right pad-right">
                <form action="/accounts/add-friend">
                  <button class="btn btn-primary btn-md" id="add-friend">Add Friend</button>
                </form>
              </div>
            </ul>

            {% else %}
            <ul class='nav navbar-nav navbar-right'>
              <li>
              <form class="navbar-form navbar-right" method="post" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                <input id="inputUsername" class="form-control" name="username"
                  type="text" placeholder="Username">
                <input id="inputPassword" class="form-control" name="password"
                  type="password" placeholder="Password">
                <button class="btn btn-primary btn-md" id="login-submit" type="submit">Sign in</button>
              </form>
              </li>

              <ul>
                <li>
                <div>
                  <a class="new-account" href="/accounts/new-account/">Create Account</a>
                </div>
                </li>
              </ul>

            </div>
          {% endif %}
          </ul>
        </div>

      <div class='container'>
          {% if messages %}
          <ul class="alert-danger">
            {% for message in messages %}
            <p{% if message.ERROR %} class="{{ message.tags }}" {% endif %}>
              {% if message.extra_tags == "login-error" %}
                {{ message }}
                {% endif %}
              </p>
              {% endfor %}
            </ul>
            {% endif %}

            {% if messages %}
            <ul class="alert-danger">
              {% for message in messages %}
              <p {% if message.ERROR %} class="{{ message.tags }}" {% endif %}>
                {% if message.extra_tags == "event-error" %}
                {{ message }}
                {% endif %}
              </p>
              {% endfor %}
            </ul>
            {% endif %}
        </div>

    <div class="container">
      <div class="calendar-table">
        {% load calendarify %}
        <span id="calendarify">{% calendarify year month event_list %}</span>
      </div>
    </div>

  </body>
</html>

cal/templates/event.html
{% extends 'event_base.html' %}

{% block title %}New Event{% endblock %}

{% block header_text %}Create New Event{% endblock %}

cal/templates/event_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/cal/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/cal/bootstrap-datetimepicker.css">
    <link rel="stylesheet" href="/static/cal/calendar.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">

    <script type="text/javascript" src="/static/cal/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/static/cal/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/cal/moment.js"></script>

    <script type="text/javascript" src="/static/cal/bootstrap-datetimepicker.min.js"></script>
  </head>

  <body>
    <h2 class="centre-head">{% block header_text %}{% endblock %}</h2>
    <div class="container">
      <div class="centre-form">
        <div class="row">
          <div class='col-sm-8'>
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
                </div>
              {% endfor %}
            {% endif %}

            <form class="form-inline" method="post">
              {% csrf_token %}

              <div class="wrapper">
                <div class="fieldWrapper form-inline floatLeft">
                  <label for="{{ form.title.id_for_label }}">Title</label>
                  <li>{{ form.title }}</li>
                </div>
                <div class="fieldWrapper form-inline floatRight">
                  <label for="{{ form.location.id_for_label }}">Location</label>
                  <li>{{ form.location }}</li>
                </div>
              </div>

              <div class="wrapper">
                <div class="fieldWrapper form-inline floatLeft">
                  <label for="{{ form.start_date.id_for_label }}">Start Date</label>
                  <li>{{ form.start_date }}</li>
                </div>
                <div class="fieldWrapper form-inline floatRight">
                  <label for="{{ form.end_time.id_for_label }}">Start Time</label>
                  <li>{{ form.end_time}}</li>
                </div>
              </div>

              <div class="wrapper">
                <div class="fieldWrapper form-inline floatLeft">
                  <label for="{{ form.end_date.id_for_label }}">End Date</label>
                  <li>{{ form.end_date }}</li>
                </div>
                <div class="fieldWrapper form-inline floatRight">
                  <label for="{{ form.end_time.id_for_label }}">End Time</label>
                  <li>{{ form.end_time}}</li>
                </div>
              </div>

              <div class="fieldWrapper">
                <label for="{{ form.description.id_for_label }}">Description</label>
                <li>{{ form.description }}</li>
              </div>

              <div class="wrapper">
                <div class="fieldWrapper form-inline floatLeft">
                  <label for="{{ form.attendees.id_for_label }}">Attendees</label>
                  <li>{{ form.attendees }}</li>
                </div>
                <div class="fieldWrapper form-inline floatRight">
                  <p></p>
                  <button class="btn btn-primary btn-md" id="form-submit" type="submit">Submit</button>
                  {% block delete_button %}
                  {% endblock %}
                </div>
              </div>
            </form>

            {% if messages %}
            <ul class="alert-danger">
              {% for message in messages %}
              <p {% if message.ERROR %} class="{{ message.tags }}" {% endif %}>
                {% if message.extra_tags == "event-error" %}
                {{ message }}
                {% endif %}
              </p>
              {% endfor %}
            </ul>
            {% endif %}

          </div>
        </div>
      </div>
    </div>

    <script type="text/javascript">
      $(function () {
        $('.datetimepicker4').datetimepicker({
          format: 'DD/MM/YYYY'
        });
      });
      $(function () {
        $('.datetimepicker3').datetimepicker({
          format: 'HH:mm',
        });
      });
    </script>
  </body>
</html>

cal/templates/new_event.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>New Event</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">

  </head>
  <body>
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}

      <form class="new-event-form" method="post">
        {% csrf_token %}
        {{ form }}
        <input id="submit" type="submit" value="Create" action="/"/>
      </form>

      <script src="js/bootstrap.min.js"></script>
  </body>
</html>

cal/templates/newaccount.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>New Account</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">

  </head>
  <body>
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}

      <form class="new-account-form" method="post">
        {% csrf_token %}
        {{ form }}
        <input id="submit" type="submit" value="Create"/>
      </form>

      <script src="js/bootstrap.min.js"></script>
  </body>
</html>

cal/templates/view_event.html
{% extends 'event_base.html' %}

{% block title %}View Event{% endblock %}

{% block header_text %}Edit Event{% endblock %}

{% block delete_button %}
<a class="btn btn-primary btn-md" id="event-delete" href="{% url 'cal:delete_event' id=id %}">Delete</a>
{% endblock %}